<CalcButton@Button>:
    color: .8,.9,0,1
    font_size: self.size_hint_y/10

<CalcBoxLayout@BoxLayout>:
    orientation: "horizontal"
    size_hint_y: 1
    padding: (1,1)
    spacing: 1



CalculatorRoot:
<CalculatorRoot>:
    orientation: "vertical"
    spacing: 1

    Label:
        id: screen_calc
        size: (self.size_hint_x/2, self.size_hint_y)
        padding: (5,5)
        font_size: 32
        color: 0,0,0,1
        text: root.screen_output
        size_hint_y: 2
        canvas.before:
            Color:
                rgba: (.8,.8,.8,1)
            Rectangle:
                pos: self.pos
                size: self.size


    CalcBoxLayout:
        orientation: "horizontal"
        size_hint_y: 2
        CalcButton:
            text: "MC"
            on_press: root.pressAnyButton("MCLEAN")
        Button:
            text: "MR"
            on_press: root.pressAnyButton("MRECOV")
        Button:
            text: "MS"
            on_press: root.pressAnyButton("MSAVE")
        Button:
            text: "M+"
            on_press: root.pressAnyButton("MPLUS")
    BoxLayout:
        padding: (5,5)
        orientation: "horizontal"
        size_hint_y: 1
        Label:
            text: ":D"
        Button:
            text: "CE"
            on_press: root.pressAnyButton("CLEARENTRY")
        Button:
            text: "C"
            on_press: root.pressAnyButton("CLEAN")

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: 1.5
        Button:
            text: "7"
            on_press: root.pressAnyButton("7")
        Button:
            text: "8"
            on_press: root.pressAnyButton("8")
        Button:
            text: "9"
            on_press: root.pressAnyButton("9")
        Button:
            text: "/"
            on_press: root.pressAnyButton("DIVIS")

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: 1.5
        Button:
            text: "4"
            on_press: root.pressAnyButton("4")
        Button:
            text: "5"
            on_press: root.pressAnyButton("5")
        Button:
            text: "6"
            on_press: root.pressAnyButton("6")
        Button:
            text: "*"
            on_press: root.pressAnyButton("MULTIP")

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: 1.5
        Button:
            text: "1"
            on_press: root.pressAnyButton("1")
        Button:
            text: "2"
            on_press: root.pressAnyButton("2")
        Button:
            text: "3"
            on_press: root.pressAnyButton("3")
        Button:
            text: "-"
            on_press: root.pressAnyButton("SUBT")

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: 1.5
        Button:
            text: "0"
            on_press: root.pressAnyButton("0")
        Button:
            text: "."
            on_press: root.pressAnyButton(".")
        Button:
            text: "="
            on_press: root.pressAnyButton("EQUAL")
        Button:
            text: "+"
            on_press: root.pressAnyButton("ADD")

